name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # from the ktlint wiki page https://pinterest.github.io/ktlint/1.0.1/install/cli/
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.0.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - run: ktlint
