name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lib1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VideoGenerator/example
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@v2

      - name: Give exec permission for ./gradlew
        run: chmod +x ./gradlew
      - name: Assemble the apk
        run: ./gradlew assemble
      - name: Download test assets
        run: ./gradlew downloadAndUnzipTestAssets
      - name: Run Tests
        run: ./gradlew test
  lib2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DifferenceGenerator
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@v2

      - name: Download test assets
        run: ./gradlew downloadAndUnzipTestAssets
      - name: Run Tests
        run: ./gradlew test
